name             'crf-rancid'
maintainer       'Crossroads Foundation Ltd'
maintainer_email 'itdept@crossroads.org.hk'
license          'Apache 2.0'
description      'Installs/Configures crf-rancid'
long_description 'Installs/Configures crf-rancid'
version          '0.1.0'
